import { GetServerSideProps } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { Components} from '../Glasses'

interface HomeProps {
  glasses: Components[],

}

{/* 
export const getServerSideProps: GetServerSideProps <HomeProps> =  async () => {
  const response = await fetch("https://wc-api.dresden.vision/wc/glasses/non-prescription-glasses");
  const glassesResponse: GlassesResponse = await response.json();
  return {
    props: { glasses: glassesResponse.components }
  }
}

*/}

export default function Home({glasses} : HomeProps) {
  return (
    <>
      <Head>
        <title>Vend</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-white-200 min-h-screen'>
        <div >
          <div className='flex justify-center'>index</div>

        </div>
        
      </main>
    </>
  )
}
